### ISSUE TITLE
[Feature Request] Support for running cbwebreader within docker

### ISSUE THREAD

**Issue by apoclyps** [ajurna/cbwebreader#3]
#### Request

I would like to make use of  `cbwebreader` on different operating systems without the need to install dependencies on the host system because the ability to deploy this application makes it incredibly useful to myself (and potentially others).

The feature I would like to request is to implement support for docker to allow the application to be run anywhere, and to aid in making the developer experience for contributing to this repository easier.

### Proposal

I have prepared the following PR as a proposal to merge back into this project. I would love to know if this is something you would be open too, and if so, would you like to review it to ensure it doesn't conflict with your existing use case. 

https://github.com/apoclyps/cbwebreader/pull/1

I would be more than happy to discuss this feature request/PR further, you can reach me on all the social media sites as @apoclyps.

**Comment by ajurna** [comment]
It looks good, as you can tell i was looking into doing this myself but i got waylay-ed by other stuff.
the pr looks good. i've even migrated to postgres myself in my newer stuff and found it quite good.

my only concern is  i did run into issues with the not using the ,decode(). but if that's resolved in django 2,2 then i'm happy to merge in.

If you have any other idea's for features please let me know. It's nice to know someone other than myself is using this :).

**Comment by apoclyps** [comment]
Thanks for the quick feedback. I will add some additional test coverage around the `.decode()` functionality for added confidence before opening the PR.

I'll raise some feature requests this evening, as I have a few ideas to enrich the UX and provide some useful metadata around issues. 

Thanks for building an awesome project. I can't wait to get my library imported and start making use of it. Also, if you're opening to discussing ideas you can find me on the [Irish Technology Community](http://irishtechcommunity.com/)y slack channel as @apoclyps.

**Comment by apoclyps** [comment]
I've taken a manual test pass over the docker changes and found no regressions, additionally, the status checks are green on https://github.com/ajurna/cbwebreader/pull/7 and the changes look good (in regards to the usage of `.decode()`. I've decided to forgo adding additional tests at this stage as there are a few patterns I'd like to implement first e.g. [Arrange/Act/Assert](http://wiki.c2.com/?ArrangeActAssert) and view level tests.
