### ISSUE TITLE
impossible to login with a new user

### ISSUE THREAD

**Issue by Daniere-Mathieu** [ajurna/cbwebreader#78]
hello , i actually try to log with a new generate account for guest who want to read on my vps , when i log to the account with the password and the good login , nothing append , no error message , no network request (i'm using the docker-compose and i can login with my superUser account)

**Comment by ajurna** [comment]
I've just taken a look there. i can reproduce the problem. lemme take a look and i'll push a fix hopefully soon

**Comment by ajurna** [comment]
just to note, you will need to reset the users password and that will work after you update.

**Comment by ajurna** [comment]
due to form weirdness the login screen was submitting on first post. this caused a page reload and the login didnt happen. i've resolve this now.
